name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  Job:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.401
      - name: Dotnet Restore
        run: dotnet restore
      - name: Dotnet Build
        run: dotnet build --configuration Release --no-restore -o "./bin"
      - name: Dotnet Test
        run: dotnet test --no-restore --verbosity normal
      - name: Dotnet Publish
        shell: cmd
        env:
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_URL: https://nuget.pkg.github.com/jacobapoirier9/index.json
        run: dotnet nuget push "./bin/*.nupkg" --api-key %NUGET_GETY% --source %NUGET_URL% --no-service-endpoint
